version: '3'

services:
  mongo:
    image: mongo:3.2.12
    ports:
      - "27017"
    volumes:
      - mongo-data:/data/db
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./services/nginx/certs:/etc/ssl/certs/
    ports:
      - "8443:443"
    links:
      - app
    depends_on:
      - app
  app:
    image: "fish"
    build:
      context: "."
    volumes:
      - "./start.js:/fish/start.js"
      - "./app:/fish/app"
      - "./lib:/fish/lib"
    links:
      - mongo
    depends_on:
      - mongo
    ports:
      - "8002:8002"
      - "8003:8003"
      - "8080:8080"
    environment:
      NODE_PATH: "/"

volumes:
  mongo-data: