service: projectfish

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: eu-central-1

functions:
  - "${file(lib/handlers/authentication/authentication.serverless.yml)}"
  - "${file(lib/handlers/user/user.serverless.yml)}"
  - "${file(lib/handlers/settings/settings.serverless.yml)}"

plugins:
  - serverless-offline
