"use strict"

exports.BAD_REQUEST = 400
exports.UNAUTHORIZED = 401
exports.FORBIDDEN = 403
exports.NOT_FOUND = 404
exports.INTERNAL_SERVER_ERROR = 500
exports.NOT_IMPLEMENTED = 501
exports.SERVICE_UNAVAILABLE = 503
